stages:
- runall-and-report-to-github-pending
- build
- collate
- report-to-github-done
  
###############################################################################
# report result to github
###############################################################################
runall-and-report-to-github-pending:
  image: python:2.7
  stage: runall-and-report-to-github-pending
  script:
  - python reportCiResult.py "gitlab-ci" "pending"
  when: manual
  allow_failure: false

# Build
build_osx_runtime:
  stage: build
  tags:
    - bokken-job
  variables:
    BOKKEN_VM: build_osx_runtime_vm
    BOKKEN_JOB: |
      resources:
        - name: build_osx_runtime_vm
          image: buildfarm/mac:latest
          flavor: m1.mac
          type: Unity::VM::osx
          num_instances: 1
          config:
            env_vars:
              - PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
  script:
  - git submodule update --init --recursive
  - cp .yamato/config/Stevedore.conf ~/Stevedore.conf
  - cd external/buildscripts
  - ./bee
  - cd ../..
  - perl external/buildscripts/build_runtime_osx.pl --stevedorebuilddeps=1
  - mkdir -p incomingbuilds/osx-i386
  - cp -r builds/ incomingbuilds/osx-i386/
  artifacts:
    paths:
    - incomingbuilds/osx-i386
    expire_in: 1 week
# Important! Do not remove this after_script!!  
  after_script:
    - /opt/post_build_script.sh

build_osx_classlibs:
  stage: build
  tags:
    - bokken-job
  variables:
    BOKKEN_VM: build_osx_classlibs_vm
    BOKKEN_JOB: |
      resources:
        - name: build_osx_classlibs_vm
          image: buildfarm/mac:latest
          flavor: m1.mac
          type: Unity::VM::osx
          num_instances: 1
          config:
            env_vars:
              - PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
  script:
  - git submodule update --init --recursive
  - cp .yamato/config/Stevedore.conf ~/Stevedore.conf
  - cd external/buildscripts
  - ./bee
  - cd ../..
  - perl external/buildscripts/build_classlibs_osx.pl --stevedorebuilddeps=1
  - mkdir -p incomingbuilds/classlibs
  - cp -r ZippedClasslibs.tar.gz incomingbuilds/classlibs/
  - cd incomingbuilds/classlibs
  - tar -pzxf ZippedClasslibs.tar.gz
  - rm -f ZippedClasslibs.tar.gz
  - cd ../..
  artifacts:
    paths:
    - incomingbuilds/classlibs
    expire_in: 1 week
# Important! Do not remove this after_script!!  
  after_script:
    - /opt/post_build_script.sh

build_android:
  stage: build
  tags:
    - bokken-job
  variables:
    BOKKEN_VM: build_android_vm
    BOKKEN_JOB: |
      resources:
        - name: build_android_vm
          image: buildfarm/mac:latest
          flavor: m1.mac
          type: Unity::VM::osx
          num_instances: 1
          config:
            env_vars:
              - PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
  script:
  - git submodule update --init --recursive
  - cp .yamato/config/Stevedore.conf ~/Stevedore.conf
  - cd external/buildscripts
  - ./bee
  - cd ../..
  - perl external/buildscripts/build_runtime_android.pl --stevedorebuilddeps=1
  - mkdir -p incomingbuilds/android/
  - cp -r builds/* incomingbuilds/android/
  artifacts:
    paths:
    - incomingbuilds/android
    expire_in: 1 week
# Important! Do not remove this after_script!!  
  after_script:
    - /opt/post_build_script.sh

build_win:
  stage: build
  tags:
    - bokken-job
  variables:
    BOKKEN_VM: build_win_vm
    BOKKEN_JOB: |
      resources:
        - name: build_win_vm
          image: platform-foundation/windows-mono-bokken:latest
          flavor: b1.xlarge
          type: Unity::VM
  script:
  - git submodule update --init --recursive
  - perl external/buildscripts/build_runtime_win64.pl --stevedorebuilddeps=1
  - powershell mkdir -p incomingbuilds/win64
  - powershell cp -r builds/* incomingbuilds/win64/
  artifacts:
    paths:
    - incomingbuilds/win64
    expire_in: 1 week
# Important! Do not remove this after_script!!
  after_script:
    - C:\Users\builduser\post_build_script.bat

build_win_x86:
  stage: build
  tags:
    - bokken-job
  variables:
    BOKKEN_VM: build_win_x86_vm
    BOKKEN_JOB: |
      resources:
        - name: build_win_x86_vm
          image: platform-foundation/windows-mono-bokken:latest
          flavor: b1.xlarge
          type: Unity::VM
  script:
  - git submodule update --init --recursive
  - perl external/buildscripts/build_runtime_win.pl --stevedorebuilddeps=1
  - powershell mkdir -p incomingbuilds/win32
  - powershell cp -r builds/* incomingbuilds/win32/
  artifacts:
    paths:
    - incomingbuilds/win32
    expire_in: 1 week
# Important! Do not remove this after_script!!
  after_script:
    - C:\Users\builduser\post_build_script.bat

build_win_bare_minimum:
  stage: build
  tags:
    - bokken-job
  variables:
    BOKKEN_VM: build_win_bare_minimum
    BOKKEN_JOB: |
      resources:
        - name: build_win_bare_minimum
          image: platform-foundation/windows-mono-bokken:latest
          flavor: b1.xlarge
          type: Unity::VM
  script:
  - git submodule update --init --recursive
  - perl external/buildscripts/build_unityscript_bareminimum_win.pl
  - powershell mkdir -p incomingbuilds/bareminimum
  - powershell cp -r builds/* incomingbuilds/bareminimum/
  artifacts:
    paths:
    - incomingbuilds/bareminimum
    expire_in: 1 week
# Important! Do not remove this after_script!!
  after_script:
    - C:\Users\builduser\post_build_script.bat

build_linux_x64:
  stage: build
  tags:
  - buildfarm
  - linux
  script:
  - git submodule update --init --recursive
  - cd external/buildscripts
  - ./bee
  - cd ../..
  - perl external/buildscripts/build_runtime_linux.pl -build64=1 --stevedorebuilddeps=1
  - mkdir -p incomingbuilds/linux64
  - cp -r builds/* incomingbuilds/linux64/
  artifacts:
    paths:
    - incomingbuilds/linux64
    expire_in: 1 week
# Important! Do not remove this after_script!!  
  after_script:
    - /opt/post_build_script.sh

build_linux_x86:
  stage: build
  tags:
  - buildfarm
  - linux
  script:
  - git submodule update --init --recursive
  - cd external/buildscripts
  - ./bee
  - cd ../..
  - perl external/buildscripts/build_runtime_linux.pl --stevedorebuilddeps=1
  - mkdir -p incomingbuilds/linux32
  - cp -r builds/* incomingbuilds/linux32/
  artifacts:
    paths:
    - incomingbuilds/linux32
    expire_in: 1 week
# Important! Do not remove this after_script!!  
  after_script:
    - /opt/post_build_script.sh

collate_builds:
  stage: collate
  tags:
    - bokken-job
  variables:
    BOKKEN_VM: collate_ubuntu
    BOKKEN_JOB: |
      resources:
        - name: collate_ubuntu
          image: cds-ops/ubuntu-18.04-agent:v1.0.11-765607
          flavor: b1.large
          type: Unity::VM
  dependencies:
  - build_android
  - build_osx_runtime
  - build_osx_classlibs
  - build_win
  - build_win_x86
  - build_win_bare_minimum
  - build_linux_x86
  - build_linux_x64
  before_script:
  - sudo DEBIAN_FRONTEND=noninteractive apt-get update -qy && sudo DEBIAN_FRONTEND=noninteractive apt-get -qy upgrade
  - sudo apt-get install -qy zip unzip
  - sudo apt-get install -qy p7zip-full p7zip-rar
  script:
  - perl external/buildscripts/collect_allbuilds.pl
  - pwd
  - ls -al 
  artifacts:
    paths:
    - collectedbuilds/builds.7z
    - stevedore/MonoBleedingEdge.7z
    - stevedore/artifactid.txt
    expire_in: 1 week

    
###############################################################################
# report result to github
###############################################################################
report-to-github-done:failure:
  image: python:2.7
  when: on_failure
  stage: report-to-github-done
  script:
  - python reportCiResult.py "gitlab-ci" "failure"

report-to-github-done:success:
  image: python:2.7
  when: on_success
  stage: report-to-github-done
  script:
  - python reportCiResult.py "gitlab-ci" "success"