blank_issues_enabled: false
contact_links:
  - name: Mono runtime or class libraries in .NET >= 5
    url: https://github.com/dotnet/runtime/issues/new/choose
    about: For issues with runtime crashes, AOT compilation, etc in .NET 5 or later, Mono is now part of the dotnet/runtime repository.
  - name: Blazor WebAssembly issue in .NET 5 or later
    url: https://github.com/dotnet/aspnetcore/issues/new/choose
    about: Starting point for issues with Blazor WebAssembly in .NET 5 or later.
  - name: MAUI in .NET 6 or later
    url: https://github.com/dotnet/maui/issues/new/choose
    about: For issues with .NET MAUI on mobile and desktop platforms
  - name: Xamarin.Forms
    url: https://github.com/xamarin/Xamarin.Forms/issues/new/choose
    about: For issues with Xamarin.Forms
  - name: Xamarin.Android or .NET Android (.NET 6 or later)
    url: https://github.com/xamarin/xamarin-android/issues/new/choose
  - name: Xamarin.Mac or Xamarin.iOS, or .NET iOS (.NET 6 or later)
    url: https://github.com/xamarin/xamarin-macios/issues/new/choose
    
